Verthandi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
	path('', include('soporte.urls')),
	path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

soporte/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.post_list, name='post_landing'),

	path('notificaciones/', views.post_list2, name='post_noti'),
	path('notificaciones/detalles/<int:pk>', views.notiFalla, name='noti_detalle'),
    path('notificaciones/<int:pk>', views.notif_results, name='notif_results'),

	path('asistencia/<int:pk>', views.asisInf, name='asisInf'),
    path('asistencia_lista/', views.asis_list, name='asis_list'),
    path('perfil/<int:pk>/asistencias', views.in_asisInf, name='in_asisInf'),
    path('permiso_lista/', views.perm_emple_list, name='perm_emple_list'),
    path('permiso_lista/agregar', views.perm_emple_agregar, name='perm_emple_agregar'),

	path('registros1', views.registros1, name="registros1"),
	path('login/', views.login.as_view(), name='login'),

	path('aceptarusers/', views.a_us, name='a_us'),
    path('aceptarusers/?', views.a_us_bus, name='a_us_bus'),
	path('User?12@#|2aprove?/<int:pk>', views.userAP, name='userAP'),
	path('User?14@#|2aprove?/<int:pk>', views.userNE, name='userNE'),
    path('User?16@#|2aprove?/<int:pk>', views.userDES, name='userDES'),
    path('User?18@#|2aprove?/<int:pk>', views.userHAB, name='userHAB'),

	path('perfil/<int:pk>/', views.datos_u, name='datos_u'),
	path('datos/<int:pk>/edit/', views.datose, name='datose'),
    path('perfil', views.Datos1, name='datos1'),

    path('opciones_avanzadas', views.opcis_admin, name='opcisAdmin'),
    path('opciones_avanzadas/Opciones-Soporte', views.adm_sop_opcis, name='adm_sop_opcis'),
    path('opciones_avanzadas/Opciones-SoporteForm/<int:pk1>', views.adm_sop_opcisFormF, name='adm_sop_opcisFormF'),
    path('opciones_avanzadas/Opciones-Soporte/<int:pk1>', views.adm_sop_opcis_det, name='adm_sop_opcis_det'),
    path('opciones_avanzadas/Opciones-SoporteForm/Edit/<int:pk1>', views.adm_sop_opcis_detFormF, name='adm_sop_opcis_detFormF'),
    path('opcion?!d#@|reprobar!02091/<int:pk>', views.adm_sop_opcis_detNE, name='adm_sop_opcis_detNE'),


    path('opciones_avanzadas/Opciones-Soporte/Codigo', views.op_codigo, name='op_codigo'),
    path('opciones_avanzadas/Opciones-SoporteForm/Codigo/?8291Create<int:pk><int:pk1>', views.Valid1_codigo, name='Valid1_codigo'),
    path('opciones_avanzadas/Opciones-SoporteForm/Codigo/?8291Delete<int:pk>', views.Del1_codigo, name='Del1_codigo'),
    path('Acceso_Denegado', views.Error, name='Error1'),
    path('Personal-Informatica', views.personal_inf, name='personal_inf'),
    path('Personal-Coordinadores-areas', views.personal_ot_coord, name='personal_ot_coord'),
    path('Personal-Empleados-Informatica', views.personal_em_infor, name='personal_em_infor'),

    path('Personal-Informatica-v', views.personal_inf_v, name='personal_inf_v'),
    path('Personal-Informatica/Registro', views.registros_personal_inf, name='registros_personal_inf'),

    path('Reportador', views.usuarioReport, name='usuarioReport'),
    path('Reportador/Registro', views.usuarioReportRegis, name='usuarioReportRegis'),
    
    path('perfilRed/<int:pk>/', views.datos_uRed, name='datos_uRed'),

    path('Solicitud_Restablecimiento/', views.cambio_contra_sol, name='cambio_contra_sol'),
    path('Lista_Restablecimiento/', views.cambio_contra_list, name='cambio_contra_list'),
    path('Lista_Restablecimiento/<int:pk>', views.a_contra_restablecida, name='a_contra_restablecida'),
    path('contraseña/actualizacion/<int:pk>', views.a_contra_inicio, name='a_contra_inicio'),

    path('ajax/opcionesP/', views.opcisP, name='ajax_opcisP'),
    path('ajax/valid_usu/', views.validar_usuario, name='ajax_valid_usu'),
    path('ajax/valid_nivel_usu/', views.validar_nivel_usuario, name='ajax_valid_niv_usu'),
    path('ajax/opcionesP123/', views.aj_opcis_nivel, name='ajax_opcis_niveles'),

]

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    last_name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    action_flag = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class SoporteDatos(models.Model):
    usuario = models.OneToOneField(AuthUser, models.DO_NOTHING, primary_key=True)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    email = models.CharField(max_length=254, blank=True, null=True)
    fedicion = models.DateTimeField(blank=True, null=True)
    cod_area = models.IntegerField(blank=True, null=True)
    cod_nivel = models.IntegerField(blank=True, null=True)
    cedula = models.PositiveIntegerField(unique=True)

    class Meta:
        managed = False
        db_table = 'soporte_datos'


class SoporteNiveles(models.Model):
    user = models.OneToOneField(AuthUser, models.DO_NOTHING)
    nivel = models.IntegerField(db_column='Nivel', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'soporte_niveles'


class SoportePDetal(models.Model):
    nombre = models.CharField(max_length=30)
    p_opci = models.ForeignKey('SoportePOpci', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'soporte_p_detal'


class SoportePOpci(models.Model):
    nombre = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'soporte_p_opci'


class SoporteSopNotif(models.Model):
    cod_usu = models.ForeignKey(AuthUser, models.DO_NOTHING)
    descrip1 = models.ForeignKey(SoportePDetal, models.DO_NOTHING, blank=True, null=True)
    tipo_sop = models.ForeignKey(SoportePOpci, models.DO_NOTHING)
    usu_tec = models.ForeignKey(AuthUser, models.DO_NOTHING, blank=True, null=True)
    nombre = models.CharField(max_length=200)
    num_pc = models.IntegerField()
    problemaad = models.CharField(db_column='problemaAd', max_length=500)  # Field name made lowercase.
    estado_sop = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'soporte_sop_notif'

soporte/models.py
from django.db import models

from django.contrib.auth.models import User

from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.utils import timezone

# Create your models here.


class bienes_gob_categoria(models.Model):
    codigo = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return str(self.pk)+' '+(self.nombre)



class P_opci(models.Model):
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class P_detal(models.Model):
    p_opci = models.ForeignKey(P_opci, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre

class unidad2(models.Model):
    nom_unidad = models.CharField(max_length=500)
    def __str__(self):
        return self.nom_unidad

class NivelesNum(models.Model):
    nom_nivel = models.CharField(max_length=200)
    def __str__(self):
        return str(self.nom_nivel)
    
class bie_gob_bienes(models.Model):
    codigo_e = models.CharField(unique=True,max_length=100)
    cantidad = models.IntegerField()
    nombre = models.CharField(max_length=100)
    idunidad = models.ForeignKey(unidad2, on_delete=models.CASCADE)
    idcategoria = models.ForeignKey(bienes_gob_categoria, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pk)+' '+(self.nombre)

class NivelDet(models.Model):
    usuario = models.OneToOneField('auth.User',on_delete=models.CASCADE, primary_key=True, unique=True)
    nivel_tec = models.BooleanField(default=False)
    nivel_sec = models.BooleanField(default=False)
    nivel_coord_area = models.BooleanField(default=False)

class sub_area(models.Model):
    sub_area_nom = models.CharField(max_length=200)


class Codigos(models.Model):
    codigo = models.IntegerField(unique=True)
    sub_area = models.ForeignKey(P_opci,on_delete=models.CASCADE,null=True)
    cod_area = models.ForeignKey(unidad2, on_delete=models.CASCADE,null=True)
    nivel_num = models.ForeignKey(NivelesNum, on_delete=models.CASCADE)


    def __str__(self):
        return str(self.nivel_num)
        
class Datos(models.Model):
    usuario = models.OneToOneField('auth.User',on_delete=models.CASCADE, primary_key=True, unique=True)
    nombVer = RegexValidator(regex=r'^[a-zA-ZñáéíóúäëïöüÑàèìòù\s]+$', message="Solo letras para el nombre por favor.")
    nombre = models.CharField(validators=[nombVer],max_length=200)
    apellVer = RegexValidator(regex=r'^[a-zA-ZñáéíóúäëïöüÑàèìòù\s]+$', message="Solo letras para el apellido por favor.")
    apellido = models.CharField(validators=[apellVer],max_length=200)
    cedula = models.PositiveIntegerField(unique=True,validators=[MinValueValidator(1000000,message="cedula no valida."), MaxValueValidator(35000000,message="cedula no valida.")])
    email = models.EmailField(null=True)
    fedicion = models.DateTimeField(blank=True, null=True)
    cod_area = models.ForeignKey(unidad2, on_delete=models.CASCADE)
    sub_area = models.ForeignKey(P_opci,on_delete=models.CASCADE,null=True,blank=True)
    nivel_usua = models.ForeignKey(NivelesNum,on_delete=models.CASCADE,null=True)

    def publish(self):
        self.fedicion = timezone.now()
        self.save()
        #,default=NivelesNum.objects.get(pk=1).pk

    def __str__(self):
        return str(self.usuario_id)+" "+(self.nombre)



class report_usu_area(models.Model):
    usuario = models.OneToOneField('auth.User',on_delete=models.CASCADE, primary_key=True, unique=True)
    cod_area = models.ForeignKey(unidad2, on_delete=models.CASCADE, blank=True)
    nivel_usua = models.ForeignKey(NivelesNum,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return str(self.usuario)+" "+str(self.cod_area)

class estado_soporte_notif(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return str(self.nombre)


class sop_notif(models.Model):
    usu_tec = models.ForeignKey('auth.User',on_delete=models.CASCADE, null=True, related_name='Tecnico')
    cod_usu = models.ForeignKey('auth.User',on_delete=models.CASCADE, related_name='Usuario')
    tipo_sop = models.ForeignKey(P_opci,on_delete=models.CASCADE, null=True)
    descrip1 =  models.ForeignKey(P_detal,on_delete=models.CASCADE, null=True)
    nombVer = RegexValidator(regex=r'^[a-zA-ZñáéíóúäëïöüÑàèìòù\s]+$', message="Solo letras para el nombre por favor.")
    nombre = models.CharField(validators=[nombVer],max_length=200)
    num_pc = models.CharField(max_length=90,blank=True,null=True)
    nombre_e = models.CharField(max_length=190,blank=True,null=True)
    ubicacion_e = models.CharField(max_length=90,blank=True,null=True)
    categoria_e = models.CharField(max_length=90,blank=True,null=True)
    problemaAd = models.CharField(max_length=500)
    estado_sop = models.ForeignKey(estado_soporte_notif,on_delete=models.CASCADE,null=True)
    fecha_pub = models.DateTimeField(blank=True)


    def __str__(self):
        return str(self.id)

class sop_notif_mes(models.Model):
    sop_notif_tick = models.ForeignKey(sop_notif,on_delete=models.CASCADE,blank=True)
    usu_tec = models.ForeignKey(User,on_delete=models.CASCADE)
    mensaje = models.CharField(max_length=500)
    tipo_sop = models.ForeignKey(P_opci,on_delete=models.CASCADE, null=True,blank=True)
    estado_sop = models.ForeignKey(estado_soporte_notif,on_delete=models.CASCADE,null=True,blank=True)
    fecha_pub = models.DateTimeField(blank=True)

    def __str__(self):
        return str(self.id)


class asistencias_p(models.Model):
    fecha_a = models.DateField(unique=True)


class asistencia_personal(models.Model):
    n_asistencia = models.ForeignKey(asistencias_p,on_delete=models.CASCADE)
    n_empleado = models.ForeignKey(User,on_delete=models.CASCADE)
    a_emple = models.DateTimeField(null=True)
    asistente = models.BooleanField(default=False)

class reset_contra(models.Model):
    usuario_x = models.OneToOneField(User,on_delete=models.CASCADE,unique=True)
    recuperada = models.BooleanField(default=False)
    fecha_soli = models.DateTimeField()

class permisos_emple(models.Model):
    n_empleado = models.ForeignKey(User,on_delete = models.CASCADE)
    fecha_ini_per = models.DateField()
    fecha_fin_per = models.DateField()

templates/Negado.html
{% extends 'index2.html' %}

{% block title %}Error{% endblock %}
{% block tit2 %}Error{% endblock %}

{% block content %}
<div class="field" id="dentrobotoo">
	
	<h2>Acceso Denegado</h2>
	<h4>Si cree que esto fue un error</h4>
	<h4>Por favor. Comuniquese con el administrador</h4>
</div>
{% endblock %}

templates/registros1_personal.html
{% extends 'index2.html' %}
{% load humanize %}
{% load myfilters %}


{% block title %}Registro{% endblock %}


{% block content %}
<div id="content">
  <div class="header">
    <div class="header-inner">
      <!--navbar-branding/logo - hidden image tag & site name so things like Facebook to pick up, actual logo set via CSS for flexibility -->
      <a class="navbar-brand center-block" href="{% url 'login' %}" title="Home">
        <h1 class="hidden">
          <img src="img/logo.png" alt="Sasogep Logo">
          Valkyria
        </h1>
        <h2 class="logo-name">Sasogep</h2>
      </a>
      <div class="col-sm-12 text-center no_pad">
        <br>
        <br>
        <span>Sistema automatizado para el soporte técnico de la Gobernación del Estado Portuguesa </span>  
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="panel panel-default" id="loginP">
        <div class="panel-heading bnegro2">
          <h3 class="panel-title bnegro">
           Registro de Usuarios

         </h3>
       </div>
       <div class="panel-body modal-dialog-registro">

         <div class="fields" id="dentroboto">
          <form id="ProblemForm" accept-charset="UTF-8" role="form" method='post' data-url="{% url 'ajax_valid_usu' %}" data-url2="{% url 'ajax_opcis_niveles' %}" data-url3="{% url 'ajax_valid_niv_usu' %}">

           <fieldset class="" id="focusim">
             {% for field in form %}

             {% csrf_token %}
             <div class="errores">
               {% if field.errors %}
               <script type="text/javascript">
                var varka = '{{field.errors}}';
                varka = varka.replace(/\<li>/g, '');
                varka = varka.replace(/\<\/li>/g, '');
                varka = varka.replace(/\<\/ul>/g, '');
                varka = varka.replace(/\<ul class="errorlist">/g, '')
                varka = varka.replace(new RegExp("[^a-zA-ZñÑ0-9úáéíó. ]", "g"), " ");
                varka = varka.replace(/The two password fields didn t match./g,"Las dos contraseñas no coinciden.");
                varka = varka.replace('.', '.\n\n');
                varka = varka.replace(/Debe contener al menos 8 caracteres.Esta contraseña es demasiado común.Esta contraseña es completamente numérica./g,"Debe contener al menos 8 caracteres. Es demasiado común. Es completamente numérica.");

                alert(varka);
              </script>
              {% endif %}
            </div>
            {% if forloop.counter == 1%}
            <div class="form-group col-md-12">
             <div class="input-group input-group-lg">
               <span class="input-group-addon"><i class="fa fa-fw fa-user" name='username'></i></span>
               {{field|regist1:'form-control '}}
               <span class="input-group-addon2" id="spaniconBRe">
                <i class="fa fa-times" id="iconBRe" ></i>
                <i class="fa fa-check" id="iconBRe2" ></i>
              </span>

            </div>

          </div>
          {% endif %}
          {% if forloop.counter == 2%}
          <div class="form-group col-md-6 col-sm-6">
           <div class="input-group input-group-lg">
             <span class="input-group-addon"><i class="fa fa-fw fa-lock" name='username'></i></span>
             {{field|regist2:'form-control '}} 
           </div>
         </div>
         {% endif %}
         {% if forloop.counter > 2%}
         <div class="form-group col-md-6 col-sm-6">
           <div class="input-group input-group-lg">
             <span class="input-group-addon"><i class="fa fa-fw fa-lock" name='username'></i></span>
             {{field|regist3:'form-control '}} 
           </div>
         </div>

         {% endif %}


         <p></p>

         {% endfor %}

         {% for field in form2 %}
         {% if field.errors %}
         <script type="text/javascript">
          var varka = '{{field.errors}}';
          varka = varka.replace(/\<li>/g, '');
          varka = varka.replace(/\<\/li>/g, '');
          varka = varka.replace(/\<\/ul>/g, '');
          varka = varka.replace(/\<ul class="errorlist">/g, '')
          varka = varka.replace('.', '.\n\n');


          alert(varka);
        </script>
        {% endif %}

        {% csrf_token %}
        {% if forloop.counter == 1%}
        <div class="form-group col-md-6 col-sm-6">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-fw fa-user" name='username'></i></span>
            {{field|regist4:'form-control '}}
          </div>
        </div>
        {% endif %}

        {% if forloop.counter == 2%}
        <div class="form-group col-md-6 col-sm-6">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-fw fa-user" name='username'></i></span>
            {{field|regist5:'form-control '}}
          </div>

        </div>
        {% endif %}
        {% if forloop.counter == 3%}
        <div class="form-group col-md-12">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-id-card-o" name='username'></i></span>
            {{field|regist6:'form-control '}}
          </div>
        </div>
        {% endif %}

        {% if forloop.counter == 4%}
        <div class="form-group col-md-12">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-id-card-o"></i></span>
            {{field|regist6:'form-control '}}
          </div>
        </div>
        <script type="text/javascript">
        </script>
        {% comment %}
        <div class="form-group col-md-12">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-id-card-o" name='username'></i></span>
            <input list="cod_area2" name="cod_area" required id="id_cod_area" class="form-control ">
            <datalist id="cod_area2">
              {% for campo in formOpti %}
              <option value="{{campo}}">

              </option>
              {% endfor %}
            </datalist>

          </div>
        </div>
        {% endcomment %}
        {% endif %}
        {% if forloop.counter == 5 %}
        <div class="form-group col-md-12">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-id-card-o" name='username'></i></span>
            {{field|regist6:'form-control '}}
          </div>
        </div>
        {% endif %}
        {% if forloop.counter == 6 %}
        <div class="form-group col-md-12">
          <div class="input-group input-group-lg" id="id_sub_area2">
            <span class="input-group-addon"><i class="fa fa-id-card-o" name='username'></i></span>
            {{field|regist6:'form-control '}}
          </div>
        </div>
        {% endif %}


        <p></p>

        {% endfor %}
        {% for field in form3 %}
        {% comment %}
        {% if field.errors %}
        <script type="text/javascript">
          var varka = '{{field.errors}}';
          varka = varka.replace(/\<li>/g, '');
          varka = varka.replace(/\<\/li>/g, '');
          varka = varka.replace(/\<\/ul>/g, '');
          varka = varka.replace(/\<ul class="errorlist">/g, '')
          varka = varka.replace('.', '.\n\n');


          alert(varka);
        </script>
        {% endif %}
        {% endcomment %}
        {% csrf_token %}
        {% if forloop.counter == 1%}
        <div class="form-group col-md-12 col-sm-12">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-id-card-o" name='username'></i></span>
            {{field|regist7:'form-control '}}
          </div>
        </div>
        {% endif %}

        {% if forloop.counter == 2%}
        <div class="form-group col-md-6 col-sm-6">
          <div class="input-group input-group-lg">
            <span class="input-group-addon"><i class="fa fa-fw fa-user" name='username'></i></span>
            {{field|regist5:'form-control '}}
          </div>

        </div>
        {% endif %}
        {% endfor %}

        <button class="btn btn-lg btn-primary btn-block" type="submit">Registrarse</button>
      </fieldset>
      <br>


    </form>

  </div>
</div>
</div>
</div>
</div>
<!-- /row -->
</div>
</div>






{% endblock %}

{% block modals%}

<script type="text/javascript">
asd = $("#id_sub_area");
asd.css('display', 'block');
</script>



<script type="text/javascript">
  function check (e) {
    var url = $("#ProblemForm").data('url');
    var username = $(this).val();
    var element = document.getElementById("id_username");
    var variable;
        /*
        for (variable in $(this)) {
          console.log(variable);
        }
        */
        username = username.replace(new RegExp("[ ]+", "g"), "");

        if (username) {
          $.ajax({
            url: url,
            data: {
              'username': username
            },
            dataType: 'json',
            success: function (data) {
              if (data.usuario_tomado) {
                $("#id_username").removeClass("form-control-accept");
                $("#spaniconBRe").removeClass("form-control-accept");
                $("#id_username").addClass("form-control-neg");
                $("#spaniconBRe").addClass("form-control-neg");
                $("#spaniconBRe").css('display', 'table-cell');
                $("#iconBRe2").css('display', 'none');
                $("#iconBRe").css('display', 'inline');

                /* $("#id_username").classList.add("form-control-neg"); */
                /*alert("Un usuario con este nombre existe.");*/
              }
              else {
                $("#id_username").removeClass("form-control-neg");
                $("#spaniconBRe").removeClass("form-control-neg");
                $("#id_username").addClass("form-control-accept");
                $("#spaniconBRe").addClass("form-control-accept");

                $("#spaniconBRe").css('display', 'table-cell');
                $("#iconBRe").css('display', 'none');
                $("#iconBRe2").css('display', 'inline');
              }
            }
          });

        }
        else if (!username) {
          $("#id_username").removeClass("form-control-neg");
          $("#spaniconBRe").removeClass("form-control-neg");
          $("#id_username").removeClass("form-control-accept");
          $("#spaniconBRe").removeClass("form-control-accept");
          $("#spaniconBRe").css('display', 'none');
          $("#iconBRe").css('display', 'none');
          $("#iconBRe2").css('display', 'none');

        }
        
      }
      var userid = $("#id_username");
      userid.change(check).change();




      


    </script>



    <script type="text/javascript">

    </script>

    {% endblock %}